export const EDIT_MODE = "EDIT_MODE";
export const EXIT_EDIT_MODE = "EXIT_EDIT_MODE";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const FECH_CATEGORIES_FALILED = "FECH_CATEGORIES_FALILED";

export const SET_AUTHORS = "SET_AUTHORS";
export const FECH_AUTHORS_FALILED = "FECH_AUTHORS_FALILED";